name: Build Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: volta-cli/action@v4

      - uses: pnpm/action-setup@v4

      - run: pnpm install

      - run: pnpm build

      - uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist.zip

      - uses: actions/upload-artifact@v6
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md

  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: dist
      - uses: actions/download-artifact@v4
        with:
          name: CHANGELOG.md

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md

      - id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip
          asset_name: Disable-CSP-${{ github.ref_name }}.zip
          asset_content_type: application/zip
